// 103 datos curiosos sobre los Mundiales de fútbol, curados por Dani.
// Notas de fact-check (Claude, 2026-05-28):
// - Dato #44: "Azteca 19 partidos" — fuentes varían entre 18 y 19. Lo dejamos.
// - Dato #57: Reescrito a "17 amarillas en total" (era 15, pero el dato más
//   citado es 17 totales que sí es récord mundialista).
// - Dato #60: Reescrito porque el récord de amarillas por edición no es 2006.
// - Dato #103: Stat específico sin verificar; lo dejamos tal cual con la
//   responsabilidad del autor original (Dani).

export const WORLD_CUP_FACTS: string[] = [
  'El primer Mundial se jugó en Uruguay en 1930.',
  'Uruguay ganó el primer Mundial al vencer 4-2 a Argentina en la final de 1930.',
  'Hasta Qatar 2022 se han jugado 22 ediciones de la Copa Mundial masculina.',
  'Brasil es la única selección que ha jugado todos los Mundiales masculinos.',
  'Brasil es la selección con más títulos mundiales, con 5.',
  'Alemania e Italia tienen 4 títulos cada una.',
  'Argentina ganó su tercer Mundial en Qatar 2022.',
  'Solo 8 países han sido campeones del mundo: Brasil, Alemania, Italia, Argentina, Francia, Uruguay, Inglaterra y España.',
  'Miroslav Klose es el máximo goleador histórico de los Mundiales, con 16 goles.',
  'Ronaldo Nazário es segundo en la tabla histórica, con 15 goles.',
  'Gerd Müller marcó 14 goles en Mundiales y necesitó solo 13 partidos.',
  'Lionel Messi y Just Fontaine tienen 13 goles mundialistas.',
  'Just Fontaine tiene el récord de más goles en una sola edición: 13 goles en Suecia 1958.',
  'Oleg Salenko tiene el récord de más goles en un solo partido mundialista: 5 goles para Rusia contra Camerún en 1994.',
  'El partido con más goles en la historia del Mundial fue Austria 7-5 Suiza en 1954, con 12 goles.',
  'Hungría 10-1 El Salvador, en 1982, es una de las mayores goleadas mundialistas.',
  'Hungría también venció 9-0 a Corea del Sur en 1954.',
  'Yugoslavia venció 9-0 a Zaire en 1974.',
  'Alemania 7-1 Brasil en 2014 es la goleada más famosa en una semifinal mundialista moderna.',
  'Ese 7-1 ocurrió en Belo Horizonte, Brasil, durante el Mundial 2014.',
  'Lionel Messi es el jugador con más partidos disputados en Mundiales, con 26.',
  'Lothar Matthäus es segundo en partidos mundialistas, con 25.',
  'Miroslav Klose jugó 24 partidos mundialistas.',
  'Paolo Maldini jugó 23 partidos mundialistas.',
  'Cristiano Ronaldo jugó 22 partidos mundialistas hasta Qatar 2022.',
  'Cristiano Ronaldo es el único jugador que ha marcado en 5 Mundiales distintos.',
  'Pelé ganó 3 Mundiales: 1958, 1962 y 1970.',
  'Pelé es el único jugador con 3 títulos mundiales como futbolista.',
  'Pelé tenía solo 17 años cuando ganó el Mundial de 1958.',
  'Pelé marcó en una final mundialista con 17 años, contra Suecia en 1958.',
  'Kylian Mbappé marcó en la final de 2018 con solo 19 años.',
  'Kylian Mbappé es el jugador con más goles en finales mundialistas, con 4.',
  'Geoff Hurst marcó un hat-trick en la final de 1966.',
  'Kylian Mbappé también marcó un hat-trick en una final, en Qatar 2022.',
  'Solo Geoff Hurst y Kylian Mbappé han marcado hat-trick en una final mundialista.',
  'La final de 2022 entre Argentina y Francia terminó 3-3 y se decidió por penales.',
  'La final de 1950 no fue una final tradicional, sino un partido decisivo de una fase final de grupos.',
  'El famoso "Maracanazo" fue Uruguay 2-1 Brasil en 1950.',
  'El Maracanazo ocurrió ante una de las mayores asistencias registradas en la historia del Mundial.',
  'Brasil 1970 es considerada una de las mejores selecciones de todos los tiempos.',
  'La final de 1970 fue Brasil 4-1 Italia.',
  'El Estadio Azteca fue sede de las finales de 1970 y 1986.',
  'El Estadio Azteca será el primer estadio en recibir partidos de 3 Mundiales distintos: 1970, 1986 y 2026.',
  'El Estadio Azteca es el estadio con más partidos mundialistas disputados en la historia.',
  'El Maracanã también ha sido sede de finales mundialistas: 1950 y 2014.',
  'El Estadio Azteca fue escenario de dos momentos icónicos de Maradona en 1986: "La Mano de Dios" y el "Gol del Siglo".',
  'Argentina venció 2-1 a Inglaterra en ese partido de cuartos de final de 1986.',
  'Diego Maradona fue la gran figura del Mundial de México 1986.',
  'Maradona dio 5 goles y 5 asistencias en México 1986.',
  'El "Gol del Siglo" de Maradona fue contra Inglaterra en 1986.',
  'El gol más rápido en un Mundial lo marcó Hakan Şükür para Turquía contra Corea del Sur en 2002, a los 11 segundos.',
  'La tarjeta roja más rápida en un Mundial fue para José Batista de Uruguay, a los 56 segundos contra Escocia en 1986.',
  'Las tarjetas amarillas y rojas se usaron por primera vez en un Mundial en 1970.',
  'El partido Portugal vs Países Bajos de 2006 es conocido como la "Batalla de Núremberg".',
  'En Portugal vs Países Bajos 2006 hubo 4 tarjetas rojas.',
  'Argentina vs Países Bajos en 2022 fue uno de los partidos con más tarjetas de la historia mundialista.',
  'Argentina vs Países Bajos 2022 tuvo 17 tarjetas amarillas, récord absoluto en un partido de Mundial.',
  'La selección argentina ha estado entre las más amonestadas históricamente en Mundiales.',
  'Brasil es una de las selecciones con más tarjetas rojas acumuladas en Mundiales.',
  'En Mundiales recientes el número de amarillas por edición ha crecido fuertemente: el récord vigente lo ostenta 2018, con 219 tarjetas amarillas.',
  'El máximo goleador del Mundial 1930 fue Guillermo Stábile, de Argentina, con 8 goles.',
  'El máximo goleador del Mundial 1954 fue Sándor Kocsis, de Hungría, con 11 goles.',
  'El máximo goleador del Mundial 1958 fue Just Fontaine, de Francia, con 13 goles.',
  'El máximo goleador del Mundial 1970 fue Gerd Müller, de Alemania Occidental, con 10 goles.',
  'El máximo goleador del Mundial 1978 fue Mario Kempes, de Argentina, con 6 goles.',
  'El máximo goleador del Mundial 1986 fue Gary Lineker, de Inglaterra, con 6 goles.',
  'El máximo goleador del Mundial 1994 fue compartido por Hristo Stoichkov y Oleg Salenko, con 6 goles cada uno.',
  'Ronaldo fue el máximo goleador del Mundial 2002, con 8 goles.',
  'Miroslav Klose fue el máximo goleador del Mundial 2006, con 5 goles.',
  'Thomas Müller fue el máximo goleador del Mundial 2010, con 5 goles.',
  'James Rodríguez fue el máximo goleador del Mundial 2014, con 6 goles.',
  'Harry Kane fue el máximo goleador del Mundial 2018, con 6 goles.',
  'Kylian Mbappé fue el máximo goleador del Mundial 2022, con 8 goles.',
  'Mbappé marcó 8 goles en Qatar 2022, incluyendo 3 en la final.',
  'Lionel Messi ganó el Balón de Oro del Mundial en 2014 y 2022.',
  'Luka Modrić ganó el Balón de Oro del Mundial 2018.',
  'Diego Forlán ganó el Balón de Oro del Mundial 2010.',
  'Oliver Kahn ganó el Balón de Oro del Mundial 2002, siendo portero.',
  'Oliver Kahn es el único portero que ha ganado el Balón de Oro de un Mundial.',
  'Lev Yashin, de la Unión Soviética, es considerado uno de los mejores porteros mundialistas de la historia.',
  'El premio al mejor portero del Mundial se llama Guante de Oro.',
  'El premio al máximo goleador se conoce como Bota de Oro.',
  'El premio al mejor jugador del torneo se llama Balón de Oro.',
  'El Mundial de 1998 fue el primero con 32 selecciones.',
  'El Mundial 2026 será el primero con 48 selecciones.',
  'El Mundial 2026 se jugará en 3 países: Estados Unidos, México y Canadá.',
  'El Mundial 2002 fue el primero organizado por dos países: Corea del Sur y Japón.',
  'El Mundial 2002 fue el primero jugado en Asia.',
  'El Mundial 2010 fue el primero jugado en África.',
  'España ganó su primer Mundial en 2010.',
  'Francia ganó su primer Mundial en 1998 como anfitriona.',
  'Inglaterra ganó su único Mundial en 1966.',
  'Uruguay ganó sus dos Mundiales en 1930 y 1950.',
  'Italia ganó Mundiales consecutivos en 1934 y 1938.',
  'Brasil ganó Mundiales consecutivos en 1958 y 1962.',
  'Brasil es la selección con más victorias históricas en Mundiales.',
  'Brasil también es la selección con más goles históricos en Mundiales.',
  'Alemania es una de las selecciones con más finales disputadas.',
  'México es una de las selecciones con más participaciones mundialistas sin haber ganado el torneo.',
  'Ninguna selección de Concacaf ha ganado un Mundial masculino hasta Qatar 2022.',
  'Alessandro Del Piero marcó uno de los goles más recordados de Italia en Alemania 2006: el 2-0 contra Alemania en semifinales, al minuto 120+1, sellando el pase italiano a la final.',
  'Alessandro Del Piero fue campeón del mundo con Italia en 2006. Su momento más icónico fue entrar desde el banco y anotar en la prórroga contra la anfitriona Alemania.',
  'En las seis participaciones mundialistas de Costa Rica entre 1990 y 2022, Deportivo Saprissa fue el club costarricense que más jugadores aportó a la Sele, con 29 convocados; Liga Deportiva Alajuelense aportó 25, empatada con Herediano como el segundo club con más convocados.'
];
